### ISSUE TITLE
Define how to match requirements

### ISSUE THREAD

**Issue by rawagner** [eclipse/reddeer#1627]
@JRE(matcher = matcherClass.class)

MatcherClass extends RequirementsMatcher
matcherClass is optional, requirement defines the default one

values can be

matchesString="(1.7,1.8)"
matchesEnum
matchesInt
matchesDouble
and all other supported annotation types
maybe all should be arrays

**Comment by mlabuda** [comment]
Done as part of #1743

**Comment by mlabuda** [comment]
Closing
