### ISSUE TITLE
Check hierarchy of handlers in gef/graphiti

### ISSUE THREAD

**Issue by rawagner** [eclipse/reddeer#1679]

**Comment by apodhrad** [comment]
Found the following handlers
* Gef
  - EditPartHandler
  - FigureHandler
  - PaletteHandler
  - ViewerHandler

* Graphiti
  - ContextButtonHandler
  - GraphitiEditPartHandler

and none of the above handlers manipulates with control, item nor widget.

**Comment by apodhrad** [comment]
Closed as nothing to do
