### ISSUE TITLE
Define version format and update the appropriate documentation

### ISSUE THREAD

**Issue by apodhrad** [eclipse/reddeer#1724]
We should define version format for various builds CI, CR, Snapshot, Final etc. plus timestamp.

WDYT about the folowing?
   - 2.0.0.CI-v20170525115-1234
   - 2.0.0.Final-v20170525115-1234

**Comment by mlabuda** [comment]
Not sure whether it is worth of it, our cycle does not change in so called CR phase... Snapshost / CI is almost same. I would keep it simple - SNAPSHOT and Final.

**Comment by apodhrad** [comment]
So, we could have just two aliases and two update sites as follows

* SNAPSHOT
  - http://download.eclipse.org/reddeer/snapshots
* Final
  - http://download.eclipse.org/reddeer/releases

**Comment by apodhrad** [comment]
Since the default BUILD_ALIAS is 'CI' I suggest to create a new update site at
http://download.eclipse.org/reddeer/integration

**Comment by rawagner** [comment]
already done
