### ISSUE TITLE
First screenshot is blank on rhel

### ISSUE THREAD

**Issue by odockal** [eclipse/reddeer#1729]
Find out why and repair the issue that causes that first screenshot recorded after test failures is blank on rhel slave on jenkins. Also, figure out why is this happening on ubuntu for all screenshots, not only the first one.

**Comment by odockal** [comment]
We need to verify that screenshots are actually not working on ubuntu.

**Comment by luvalach** [comment]
It seems that screenshot on RHEL is blank because of some bug in SWT or in Cairo (which is platform-specific library used by SWT).

I didn't find how to fix it but I implemented simple workaround, see PR [https://github.com/eclipse/reddeer/pull/1892](https://github.com/eclipse/reddeer/pull/1892).

**Comment by luvalach** [comment]
PR has been merged. Could anybody close this issue?

**Comment by odockal** [comment]
Resolved with #1892.
