### ISSUE TITLE
Change url for requirements

### ISSUE THREAD

**Issue by apodhrad** [eclipse/reddeer#1733]
Currently, the requirements schemas are located at
```
http://www.jboss.org/schema/reddeer/v1
```
and contain
```
namespace="http://www.jboss.org/NS/Req"
```

**Comment by apodhrad** [comment]
or we can let it as it is and update the version of to v2 which will be located at eclipse site

**Comment by apodhrad** [comment]
@rawagner wdyt?

**Comment by apodhrad** [comment]
I meant that we can leave the old schemas at jboss sites. Only the new version will be at eclipse site.

**Comment by rawagner** [comment]
IMHO it would be easier/less confusing for new users if we have them at eclipse.org

**Comment by odockal** [comment]
I must notice that I encounter one problem while trying to use the schema when I was offline. If schema and its namespace is available only online, no one could run RD while offline. Do we consider letting user to run RD offline?

**Comment by odockal** [comment]
I agree to move it to eclipse.org. But also, folder v1 was meant to be folder for newer schemas, I think. Or was it meant to be for RD v1?

**Comment by apodhrad** [comment]
Another problem is that the namespace are hardcoded :( For example,
https://github.com/eclipse/reddeer/blob/master/plugins/org.eclipse.reddeer.requirements/src/org/eclipse/reddeer/requirements/jre/JREConfiguration.java#L22

**Comment by rawagner** [comment]
we are not using xml schemas anymore. Closing
