### ISSUE TITLE
Revamp existing Configurable Requirements 

### ISSUE THREAD

**Issue by mlabuda** [eclipse/reddeer#1746]
Server requirement, Database requirement etc... have been done with enums, XSDs... Now with more flexible way it is time to refactor existing requirement and do it better. 

Configuration should be removed from declaration (attributes from Configuration should be removed from annotation of requirement declaration). Logic could be revamped.

**Comment by rawagner** [comment]
PR https://github.com/eclipse/reddeer/pull/1766
