### ISSUE TITLE
Consider disabling AERI via a system property

### ISSUE THREAD

**Issue by apodhrad** [eclipse/reddeer#1756]
```
‑Dorg.eclipse.epp.logging.aeri.ui.skipReports=true
```
as described at
https://bugs.eclipse.org/bugs/show_bug.cgi?id=473752

**Comment by rawagner** [comment]
Actually I already implemented it via API see https://github.com/eclipse/reddeer/blob/master/plugins/org.eclipse.reddeer.junit.extension/src/org/eclipse/reddeer/junit/extension/before/test/impl/DisableAERI.java
