### ISSUE TITLE
Consider using Display.asyncExec within EditorHandler.save method

### ISSUE THREAD

**Issue by odockal** [eclipse/reddeer#1760]
I have encounter situation, where during test that was checking the existence of Error dialog (MessageDialog), while calling editor.save(), I was not able to reach the shell (dialog) because it was called from within save method that is called in syncExec. 

It might be nice to have this run in asyncExec and check the state of editor (!isDirty) in WaitUntil after save logic is called and throw an exception in case that editor was not saved...

**Comment by rawagner** [comment]
@odockal is this fixed by https://github.com/eclipse/reddeer/commit/2f7cb12a22f0e028330fe51b01f48dd3a432e80b ?

**Comment by odockal** [comment]
Ehhh... Do not think so, but must check.

**Comment by odockal** [comment]
That was not the commit that repaired it, but this one: https://github.com/eclipse/reddeer/commit/bfbff8d7c285791f21a745246141d6d92b0c55ef#diff-1713c4032cdb2d6095e28196f901d1b3, and the issue was solved with RD 2.0 basically...
:)
I think we can close this.

**Comment by odockal** [comment]
Editor saving is now solved via UI controls and this actions did not run operation in syncExec probably. Cannot reproduce anymore.
