### ISSUE TITLE
All to specify when a requirement can be fulfilled

### ISSUE THREAD

**Issue by apodhrad** [eclipse/reddeer#1802]
By default, the method fulfilled is called before BeforeClass, the method cleanup is called after After. So what about implementing the following methods in a requirement?
- runBeforeClass (currently fulfilled)
- runBefore (#1793)
- runAfter (<del>currently cleanup</del>)
- runAfterClass (currently cleanup)

**Comment by apodhrad** [comment]
@rawagner @odockal wdyt?

**Comment by rawagner** [comment]
cleanup is called in AfterClass, isn't it ?

**Comment by apodhrad** [comment]
yes, you are right

**Comment by apodhrad** [comment]
this is implemented by #1804
