### ISSUE TITLE
Inappropriate wait condition in QuickFixWizard

### ISSUE THREAD

**Issue by luvalach** [eclipse/reddeer#1818]
QuickFixWizard doesn't work properly when fixing "There is no class ...". After click on Finish button the "New CDI Bean" wizard is displayed. In the Finish method there is wait condition with ShellHasChildrenOrIsNotAvailable but it doesn't work correctly because  "New CDI Bean" shell probably isn't child shell of QuickFixWizard.

**Comment by rawagner** [comment]
PR https://github.com/eclipse/reddeer/pull/1819
