### ISSUE TITLE
Issue with DefaultSection

### ISSUE THREAD

**Issue by apodhrad** [eclipse/reddeer#1831]
Whenever I use DefaultScetion I see the following error in IDE
```
The type org.eclipse.ui.forms.widgets.Section cannot be resolved. It is indirectly referenced from required .class files
```
Note that I have the dependency org.eclipse.reddeer.go

**Comment by apodhrad** [comment]
I need to add the following requirement
```
org.eclipse.uiforms
```

**Comment by apodhrad** [comment]
Probably we should reexport the missing dependency in org.eclipse.reddeer.go

**Comment by odockal** [comment]
@apodhrad Seems like valid solution.
