### ISSUE TITLE
Implement a dialog for filtering Java classes

### ISSUE THREAD

**Issue by apodhrad** [eclipse/reddeer#1835]
The implementation in Eclipse is as follows
```
org.eclipse.jdt.internal.ui.dialogs.FilteredTypesSelectionDialog
```
or its parent
```
org.eclipse.ui.dialogs.FilteredItemsSelectionDialog
```

![screenshot from 2017-10-03 14-49-11](https://user-images.githubusercontent.com/2270674/31125943-6e2bb2be-a84a-11e7-8a5d-c365b3307752.png)

**Comment by luvalach** [comment]
PR: https://github.com/eclipse/reddeer/pull/1905

**Comment by rawagner** [comment]
fixed with https://github.com/eclipse/reddeer/commit/9a18c816fee31464e9cc946607051e93df0f62d0
