### ISSUE TITLE
Add method 'activate' for activating an active wizard

### ISSUE THREAD

**Issue by apodhrad** [eclipse/reddeer#1836]
At the moment, all wizards need a shell which is set by calling
```
open()
```
or it can be directly set by calling
```
setShell(new DefaultShell(getOpenAction().getShellMatchers()));
```
which is not easy to find such workaround.

EDIT: we cannot use the above workaround since the method is protected

**Comment by rawagner** [comment]
create constructor with TimePeriod defining how log to wait for wizard shell

**Comment by luvalach** [comment]
Things changed since this issue was created. Shell is set automatically after instance of AbstractWindow's subclass is created. You can also call setShell as it is public. Anyway, I added Activate method as you wanted.

See PR: https://github.com/eclipse/reddeer/pull/1895

**Comment by rawagner** [comment]
PR merged
