### ISSUE TITLE
Editor.getMarkers returns invisible markers

### ISSUE THREAD

**Issue by rawagner** [eclipse/reddeer#1839]

**Comment by apodhrad** [comment]
I'm getting a bit different error on my F25 than on the verification job

**Comment by apodhrad** [comment]
Are you able to reproduce the error which is reported by the verification job?

**Comment by apodhrad** [comment]
Now, I am able to reproduce it on F25

**Comment by apodhrad** [comment]
there are two test methods which affect each other

**Comment by apodhrad** [comment]
fixed by #1874
