### ISSUE TITLE
Widget lookup with regexp matchers fails to find widgets containing string with special regexp characters

### ISSUE THREAD

**Issue by odockal** [eclipse/reddeer#1841]
1. Create server adapter with name "CDK 3.2+" (regular name)
2. Try to get the server item in test via ServersView.getServer("CDK 3.2+")
"+" character is the problem here. But I believe that even the dot could cause some troubles. All such characters should be prefixed with "\\" in regexp.

**Comment by jkopriva** [comment]
`new DefaultCTabItem(new WorkbenchShellReferenced(), new WithTextMatcher(new RegexMatcher("\\*?" + part.getTitle())))` in string part.getTitle must be escaped special characters.
