### ISSUE TITLE
Implement default classes for swt.Widget and swt.Control

### ISSUE THREAD

**Issue by apodhrad** [eclipse/reddeer#1845]

**Comment by apodhrad** [comment]
The reason for this enhancement was using a context menu from an editor. But this use case will be handled by #1848

**Comment by apodhrad** [comment]
Probably this enhancement is not needed. @rawagner wdyt?

**Comment by rawagner** [comment]
I think it still might be relevant.

**Comment by luvalach** [comment]
Could you review PR https://github.com/eclipse/reddeer/pull/1896 please?

**Comment by rawagner** [comment]
PR merged
