### ISSUE TITLE
Switch to photon update site

### ISSUE THREAD

**Issue by rawagner** [eclipse/reddeer#1884]

**Comment by rawagner** [comment]
we have 2 possibilities:
1. find WTP photon update site
2. remove reddeer.eclipse and reddeer.eclipse.test modules from build/test

**Comment by odockal** [comment]
I think I found WTP integration update site for photon release.
Hudson job for WTP R3.10.0 (WTP-R3_10_Integration):
https://hudson.eclipse.org/webtools/view/webtools_R3_10/job/WTP-R3_10_Integration/
which point to site where results are placed: 
http://build.eclipse.org/webtools/committers/wtp-R3.10.0-I/
and concrete update site/repository: 
http://build.eclipse.org/webtools/committers/wtp-R3.10.0-I/20180201205936/I-3.10.0-20180201205936/repository

**Comment by odockal** [comment]
WTP integrated into photon M5 update site (http://download.eclipse.org/staging/photon/).
