### ISSUE TITLE
Broken links at Wiki

### ISSUE THREAD

**Issue by luvalach** [eclipse/reddeer#1902]
There are some broken links at RedDeer Wiki - **Change log** [1] and **JavaDoc** [2] They are pointing to rhcloud.com which is not longer available. These items are already marked as deprecated so it might be removed entirely.

[1] http://jboss-reddeer.github.io/reddeer/#change_log
[2] http://javadoc-reddeer.rhcloud.com/

**Comment by odockal** [comment]
None of the links exists anymore. Closing the issue.
