### ISSUE TITLE
Improve error message when Item not found in ContextMenu

### ISSUE THREAD

**Issue by jkopriva** [eclipse/reddeer#1908]
Error message could be improved, because one part of path was found, but not the second one. Error message can be confusing for user - it looks like first part was not found and the second was found.

Source code:
new ContextMenuItem("Edit", "Manage Projects...").select();
Stacktrace:
org.eclipse.reddeer.core.exception.CoreLayerException: No menu item matching Matcher matching widgets with text that without mnenomic matches: is "Edit", Matcher matching widgets with text that without mnenomic matches: is "Manage Projects..." was found.
The following items were found on path '/Edit':
	Projects...
Connection...
	at org.eclipse.reddeer.core.lookup.MenuItemLookup.lookFor(MenuItemLookup.java:72)
	at org.eclipse.reddeer.swt.impl.menu.ContextMenuItem.<init>(ContextMenuItem.java:68)
	at org.eclipse.reddeer.swt.impl.menu.ContextMenuItem.<init>(ContextMenuItem.java:39)
	at org.jboss.tools.openshift.ui.bot.test.project.CreateNewProjectTest.testCreateNewProjectViaManageShell(CreateNewProjectTest.java:58)

**Comment by rawagner** [comment]
Im not sure how to improve this error message. Any ideas ? To me it seems quite clear..
the first part 

> 
org.eclipse.reddeer.core.exception.CoreLayerException: No menu item matching Matcher matching widgets with text that without mnenomic matches: is "Edit", Matcher matching widgets with text that without mnenomic matches: is "Manage Projects..." was found.
> 

says that menu Edit/Manage Projects was not found

the second part 

> 
The following items were found on path '/Edit':
Projects...
Connection...
> 

is a diagnostic message which says that Edit was found and also lists the items under Edit menu where it is obvious that Manage Projects... item is missing

**Comment by odockal** [comment]
I would say, it was about a lot of word "to match" that is used here and one can easily miss the message. @jkopriva  right?
