### ISSUE TITLE
Broken method "removeAllBreakpoints()" in debug.ui.views.breakpoints

### ISSUE THREAD

**Issue by djelinek** [eclipse/reddeer#1937]
There is a change in button label from "Yes" to "Remove" and it causes tests failures

**Comment by djelinek** [comment]
Noticed in Devstudio 12.0.0.GA

**Comment by rawagner** [comment]
Which RedDeer version are you using ? This should be fixed in RedDeer 2.2.0. See https://github.com/eclipse/reddeer/pull/1923

**Comment by djelinek** [comment]
Using 2.1.1.Final, I missed new RedDeer version.. I will try with new one.

**Comment by djelinek** [comment]
With RedDeer 2.2.0 there is no more this issue
