### ISSUE TITLE
Update target platform for Photon

### ISSUE THREAD

**Issue by jkopriva** [eclipse/reddeer#1948]
Target platform file for Photon is missing.

**Comment by odockal** [comment]
@apodhrad Seems like you have some experience with these files. Do you mind to take a look?

**Comment by odockal** [comment]
Also, there is missing target platform definition file for 2018-09.

**Comment by odockal** [comment]
@apodhrad ping

**Comment by jkopriva** [comment]
After discussion, we have decided to delete target files from repository.

**Comment by jkopriva** [comment]
Fixed with: https://github.com/eclipse/reddeer/pull/1971
Closing.
