### ISSUE TITLE
Problems using org.eclipse.reddeer.e4 plugin

### ISSUE THREAD

**Issue by fapdash** [eclipse/reddeer#1953]
I'm currently trying to use the `org.eclipse.reddeer.e4` plugin introduced in https://github.com/eclipse/reddeer/commit/e13032b5dda7a580ae73e1f17cf61c6aa6978c42.
I couldn't find / add it to my dependencies after installing the packages listed in https://github.com/eclipse/reddeer/blob/master/README.md#step-1---install-reddeer-to-eclipse-ide, namely RedDeer Runtime/API and RedDeer UI features. Which package should I additionally install?

I then checked out reddeer from Git and tried to run [WorkbenchPartTest.java](https://github.com/eclipse/reddeer/blob/202a7ddfacac926119b6870fc5df2ee538b3e436/tests/org.eclipse.reddeer.e4.workbench.test/src/org/eclipse/reddeer/e4/workbench/test/part/WorkbenchPartTest.java) but all the tests fail.
The instantiation of [DefaultWorkbenchPart.java](https://github.com/eclipse/reddeer/blob/202a7ddfacac926119b6870fc5df2ee538b3e436/plugins/org.eclipse.reddeer.e4.workbench/src/org/eclipse/reddeer/workbench/impl/part/DefaultWorkbenchPart.java#L23) fails with a NPE because [WorkbenchPartLookup#getWorkbenchPartWithLabel](https://github.com/eclipse/reddeer/blob/202a7ddfacac926119b6870fc5df2ee538b3e436/plugins/org.eclipse.reddeer.e4.workbench.core/src/org/eclipse/reddeer/workbench/core/lookup/WorkbenchPartLookup.java#L64) returns `null`.
To me it looks like those tests can't work since [EPartService#getParts](https://github.com/eclipse/reddeer/blob/202a7ddfacac926119b6870fc5df2ee538b3e436/plugins/org.eclipse.reddeer.e4.workbench.core/src/org/eclipse/reddeer/workbench/core/lookup/WorkbenchPartLookup.java#L66) only returns the part already opened / managed by the `EPartService` and the parts that should get tested don't get opened by the test class.
Can you please tell me what I'm missing?

**Comment by odockal** [comment]
@fapdash Hello, Thanks for reporting the issue. It really is an issue as e4 plugins are missing in feature part of project and will be added.
