### ISSUE TITLE
Aeri warning over org.eclipse.reddeer NPE 2.0.7

### ISSUE THREAD

**Issue by odockal** [eclipse/reddeer#1958]
![screenshot_20180912_211720](https://user-images.githubusercontent.com/19164299/45447914-4b25f900-b6d1-11e8-8ef9-dd0a80a0ba23.png)

**Comment by jkopriva** [comment]
Fixed with https://github.com/eclipse/reddeer/pull/1971
Closing.

**Comment by jkopriva** [comment]
Another bunch of errors:
eclipse.buildId=12.10.0.AM1-v20181119-0555-B3655
java.version=1.8.0_191
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product com.jboss.devstudio.core.product
Command-line arguments:  -data file:/home/jkopriva/devstudio_B3655/workspace/ -os linux -ws gtk -arch x86_64 -product com.jboss.devstudio.core.product

org.eclipse.e4.ui.workbench
Warning
Tue Nov 20 10:11:12 CET 2018
Removing part descriptor with the 'org.eclipse.reddeer.workbench.test.ui.views.dirtylabelview' id and the 'Workbench Dirty Test' description. Points to the invalid 'bundleclass://org.eclipse.ui.workbench/org.eclipse.ui.internal.e4.compatibility.CompatibilityView' class.


eclipse.buildId=12.10.0.AM1-v20181119-0555-B3655
java.version=1.8.0_191
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product com.jboss.devstudio.core.product
Command-line arguments:  -data file:/home/jkopriva/devstudio_B3655/workspace/ -os linux -ws gtk -arch x86_64 -product com.jboss.devstudio.core.product

org.eclipse.e4.ui.workbench
Warning
Tue Nov 20 10:11:11 CET 2018
Removing part descriptor with the 'org.eclipse.reddeer.workbench.test.ui.views.labelview' id and the 'Workbench Test' description. Points to the invalid 'bundleclass://org.eclipse.ui.workbench/org.eclipse.ui.internal.e4.compatibility.CompatibilityView' class.

eclipse.buildId=12.10.0.AM1-v20181119-0555-B3655
java.version=1.8.0_191
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product com.jboss.devstudio.core.product
Command-line arguments:  -data file:/home/jkopriva/devstudio_B3655/workspace/ -os linux -ws gtk -arch x86_64 -product com.jboss.devstudio.core.product

org.eclipse.reddeer.eclipse.test
Error
Tue Nov 20 10:11:03 CET 2018
FrameworkEvent ERROR

org.osgi.framework.BundleException: Could not resolve module: org.eclipse.reddeer.eclipse.test [1196]
  Unresolved requirement: Require-Bundle: org.eclipse.epp.logging.aeri.ide
    -> Bundle-SymbolicName: org.eclipse.epp.logging.aeri.ide; bundle-version="2.0.7.v20180504-0806"; singleton:="true"
       org.eclipse.epp.logging.aeri.ide [345]
         Unresolved requirement: Import-Package: org.apache.lucene.document; version="[7.1.0,8.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:447)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1685)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1664)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1627)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1558)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:233)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:343)

**Comment by odockal** [comment]
Only those warning left:
```
eclipse.buildId=12.10.0.AM1-v20181128-0454-B3667
java.version=1.8.0_191
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product com.jboss.devstudio.core.product
Command-line arguments:  -data file:/home/odockal/workspace12100AM1-1128/ -os linux -ws gtk -arch x86_64 -product com.jboss.devstudio.core.product

org.eclipse.e4.ui.workbench
Warning
Wed Nov 28 10:43:36 CET 2018
Removing part descriptor with the 'org.eclipse.reddeer.workbench.test.ui.views.dirtylabelview' id and the 'Workbench Dirty Test' description. Points to the invalid 'bundleclass://org.eclipse.ui.workbench/org.eclipse.ui.internal.e4.compatibility.CompatibilityView' class.

eclipse.buildId=12.10.0.AM1-v20181128-0454-B3667
java.version=1.8.0_191
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product com.jboss.devstudio.core.product
Command-line arguments:  -data file:/home/odockal/workspace12100AM1-1128/ -os linux -ws gtk -arch x86_64 -product com.jboss.devstudio.core.product

org.eclipse.e4.ui.workbench
Warning
Wed Nov 28 10:43:35 CET 2018
Removing part descriptor with the 'org.eclipse.reddeer.workbench.test.ui.views.labelview' id and the 'Workbench Test' description. Points to the invalid 'bundleclass://org.eclipse.ui.workbench/org.eclipse.ui.internal.e4.compatibility.CompatibilityView' class.
```
Follow up issue: #1977
