### ISSUE TITLE
RedDeer documentation

### ISSUE THREAD

**Issue by odockal** [eclipse/reddeer#1961]
Review actual documentation that can be found in https://github.com/eclipse/reddeer/wiki/User-Guide-2.0.

**Comment by odockal** [comment]
@jkopriva Still waiting for closing :)

**Comment by jkopriva** [comment]
@odockal Getting started part looks good, other stuff needs to be revisited.

**Comment by odockal** [comment]
@jkopriva We can create follow up issues for this cases. And take one at the time.
