### ISSUE TITLE
Move releng documentation under project codebase

### ISSUE THREAD

**Issue by odockal** [eclipse/reddeer#1982]
* Create new project folder - site/docs
* Create md files covering releng tasks: gerrit commit into simrel repo, adding new project release under eclipse, milestone release steps, final bits release process

**Comment by odockal** [comment]
@jkopriva I would like you to check the docs material. Please. Thanks.

**Comment by odockal** [comment]
@jkopriva Still waiting for closing :)

**Comment by jkopriva** [comment]
@odockal seems ok to me, but I have never done this process :(

**Comment by odockal** [comment]
@jkopriva Yeah I know. But this is more about the doc itself than about its content. Is site plugin ok? Is it readable? Can it be found?

**Comment by odockal** [comment]
@jkopriva Have it been to any use? The docs I mean.

**Comment by jkopriva** [comment]
@odockal we could add email templates or links to emails

**Comment by odockal** [comment]
@jkopriva what exactly do you mean?
