### ISSUE TITLE
Reddeer wizard creates a test plug-in with BREE of 1.8 but adds Java 1.5 to classpath

### ISSUE THREAD

**Issue by vogella** [eclipse/reddeer#1993]
See screenshot, if I use the test plug-in wizard the classpath is not the same as the BREE.

![reddeer](https://user-images.githubusercontent.com/139910/51897435-04e6e300-23af-11e9-9f80-7775b9f3e76b.png)

**Comment by vogella** [comment]
Thanks for the fix.

**Comment by odockal** [comment]
Thanks for reporting!
