### ISSUE TITLE
Align RedDeer IU according to Eclipse rules, be in compliance with issues reported by oomph

### ISSUE THREAD

**Issue by odockal** [eclipse/reddeer#2039]
See: https://download.eclipse.org/oomph/archive/simrel/reddeer.aggrcon/index.html

**Comment by merks** [comment]
Thank you for looking at the report! :-)

It would probably be best to reuse the license feature, if possible; it's less noise in your git repo.  But minimally you should ensure that each feature.properties has an exact copy of this:

https://git.eclipse.org/c/cbi/org.eclipse.license.git/plain/org.eclipse.license/feature.properties

I.e., specifically you should replace 

(Java(TM) ARchive)

with 

(Java\u2122 ARchive)

in each of your feature.properties.

**Comment by sbouchet** [comment]
Hi  @merks , 
yes, i saw all the different ways to help to create a better reddeer contribution to simrel. i'll help the team to use one of them.
