### ISSUE TITLE
Removed deprecated AERI extension

### ISSUE THREAD

**Issue by sbouchet** [eclipse/reddeer#2066]
Hi,

it seems AERI is not used anymore nor maintained. It causes some problems as it cannot start :
osgi> ss aeri
"Framework is launched."
id	State       Bundle
323	STARTING    org.eclipse.epp.logging.aeri.core_2.0.7.v20180504-0806
324	INSTALLED   org.eclipse.epp.logging.aeri.ide_2.0.7.v20180504-0806
osgi> start 324
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.epp.logging.aeri.ide [324]
  Unresolved requirement: Import-Package: org.apache.lucene.document; version="[7.1.0,8.0.0)"

So i suggest to simply remove it from reddeer. Is it still used here?

**Comment by sbouchet** [comment]
@odockal @jkopriva

**Comment by sbouchet** [comment]
i got confirmation in cross-project list that AERI is officially decommissioned: https://www.eclipse.org/lists/cross-project-issues-dev/msg17513.html

**Comment by odockal** [comment]
@sbouchet Thanks for reporting this, we do not have "hard" dependency on aeri packages, we rather have it optional. Although there is some implementation dedicated for aeri and we should defniintely remove it, but that's api change and we will need to do it while doing 3.0.0 version.

**Comment by sbouchet** [comment]
@odockal : ok ! is this major update planned? do I need to make another PR for it?

**Comment by odockal** [comment]
@sbouchet Not really.. I was thinking of making one due to the fact we got some outdated stuff like aeri that we can get rid of. This could be an opportunity.

**Comment by odockal** [comment]
testPR

**Comment by odockal** [comment]
@sbouchet hm, "testPR" does not work under issues, obviously...
