### ISSUE TITLE
org.eclipse.reddeer.eclipse.test bundle is broken (errors in dependency resolution) after move to 2023-09

### ISSUE THREAD

**Issue by odockal** [eclipse/reddeer#2219]
Testing instance of the eclipse wont start since there are frameworks errors. 
Reproducer: `mvn clean install -pl tests/org.eclipse.reddeer.eclipse.test` on master branch for 2023-09 updates.
log file: `reddeer/tests/org.eclipse.reddeer.eclipse.test/target/work/data/.metadata/.log`

Log content:
[reddeer-eclipse.log](https://github.com/eclipse/reddeer/files/12094433/reddeer-eclipse.log)

**Comment by olkornii** [comment]
There is also one failed test:
https://ci.eclipse.org/reddeer/job/reddeer.prcheck/184/testReport/org.eclipse.reddeer.e4.workbench.test.part/WorkbenchPartTest/getWidgetFromPartWhenOtherShellIsActive_no_configuration/

**Comment by odockal** [comment]
Tests are fixed now: https://ci.eclipse.org/reddeer/job/reddeer.prcheck/225/testReport/
