### ISSUE TITLE
PreferenceDialog does currently not support pop-ups after saving before focus on parent shell

### ISSUE THREAD

**Issue by thahnen** [eclipse/reddeer#2227]
## Issue

We implemented our own preference pages which show a pop-up once "Apply and Close" is clicked. The user has to acknowledge it and then is released back to the main window.

The problem is that Reddeer currently does not support that behavior, as `PreferenceDialog.ok()`[ always awaits the focus to be given back to the main window](https://github.com/eclipse/reddeer/blob/master/plugins/org.eclipse.reddeer.jface/src/org/eclipse/reddeer/jface/preference/PreferenceDialog.java#L118-L120).

## Proposed solution

Add an additional `PreferenceDialog.ok(Shell followUpShell)` implementation for this case. If you agree with me that this is a valid option, I can implement it myself.

**Comment by odockal** [comment]
@thahnen Hello there! Thanks for reporting the issue. If you could propose a PR yourself, that would be the best since we are not anymore involved in RedDeer. I can try to then do a review and if merged, you could get nightly bits to test. But I am not sure that I will be able to do a release. Depending on if we want to rebuild reddeer against latest eclipse or against last version that worked. We can try but I am not promising anything. wdyt?

**Comment by thahnen** [comment]
Hi @odockal,

thank you very much for the quick response. I'm going to propose a PR, which might take a few days.
Regarding that you're not involved in Reddeer anymore (I've also seen some messages that it is not maintained), is there any official news? I couldn't find anything here in the repo or on the Eclipse website.

**Comment by odockal** [comment]
> Add an additional PreferenceDialog.ok(Shell followUpShell) implementation for this case. If you agree with me that this is a valid option, I can implement it myself.

Solution looks fine, we just need to make sure not to break API. Adding new method is fine as long as we keep the functionality untouched for actual users of that call. 

> Reddeer anymore (I've also seen some messages that it is not maintained), is there any official news? I couldn't find anything here in the repo or on the Eclipse website.

We have sent some mail on the mailing list to the reddeer-dev and to the eclipse's cross-project-issues-dev. But I agree we can be more sound about such important change. updating readme maybe can improve the state.

**Comment by odockal** [comment]
@thahnen Here is the email: https://www.eclipse.org/lists/cross-project-issues-dev/msg19742.html

**Comment by thahnen** [comment]
@odockal maybe it is worth adding the information about the maintenance status to the README 👍

**Comment by odockal** [comment]
@thahnen -> https://github.com/eclipse/reddeer?tab=readme-ov-file#at-this-time-reddeer-is-not-actively-maintained
