### ISSUE TITLE
Enable offline testing of Red Deer

### ISSUE THREAD

**Issue by ljelinkova** [eclipse/reddeer#950]
Current issue: red deer schema

**Comment by ljelinkova** [comment]
It seems that the main problem is with the schema validation since all schemas are on the web. Storing schemas locally would need a lot of tweaks and the question is if it is worth it. Maybe simple property disabling schema validation would be good enough.

**Comment by rawagner** [comment]
Eclipse maybe have something like XML catalog - we have to check this

**Comment by rawagner** [comment]
https://wiki.eclipse.org/Using_the_XML_Catalog

**Comment by rawagner** [comment]
we removed xml schemas so reddeer works in offline mode. yay!
